import { type NextPage } from "next";
import Head from "next/head";
import ButtonGroup from "../components/ButtonGroup";
import Header from "../components/Header";
import Metric from "../components/Metric";
// import Link from "next/link";

// import { api } from "../utils/api";

const metrics = {
  club_speed: {
    title: "Club Head Speed",
    metric: "100",
    units: "MPH",
    desc: "The speed of the club head at impact",
  },
  club_angle: {
    title: "Club Face Angle",
    metric: "100",
    units: "Deg",
    desc: "The angle of the club face at impact",
  },

  ball_speed: {
    title: "Ball Speed",
    metric: "100",
    units: "MPH",
    desc: "The speed of the ball at impact",
  },
  ball_distance: {
    title: "Ball Distance",
    metric: "100",
    units: "Yds",
    desc: "The distance the ball traveled",
  },
  smash_factor: {
    title: "Smash Factor",
    metric: "100",
    units: "",
    desc: "The ratio of ball speed to club speed",
  },
  launch_angle: {
    title: "Launch Angle",
    metric: "100",
    units: "Deg",
    desc: "The angle of the ball at launch",
  },
};

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center text-center">
        <Header />
        <ButtonGroup />
        <div className="grid h-4/5 w-full items-center justify-center px-6 md:grid-cols-2">
          <section className="grid items-center justify-center md:grid-cols-2">
            {Object.entries(metrics).map(([key, value]) => (
              <Metric
                key={key}
                title={value.title}
                metric={value.metric}
                units={value.units}
                desc={value.desc}
              />
            ))}
          </section>
          <section>swing path</section>
        </div>
      </main>
    </>
  );
};

export default Home;
